name: Build and Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          always-auth: true
          registry-url: https://npm.pkg.github.com
          scope: '@juice-js'
      - run: npm ci
      - run: npm run build @juice-js/dict-builder --if-present
      - run: npm run build @juice-js/tenants --if-present
      - run: npm test
        env:
          CI: true
          NODE_AUTH_TOKEN: ${{ secrets.GIT_HUB_PAT }}
